sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t vikram276/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vikram276/react-test npm test

after_success:
  - docker build -t vikram276/multi-client ./client
  - docker build -t vikram276/multi-nginx ./nginx
  - docker build -t vikram276/multi-server ./server
  - docker build -t vikram276/multi-worker ./worker
