sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t vikram276/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vikram276/react-test npm test

after_success:
  - docker build -t vikram276/multi-client ./client
  - docker build -t vikram276/multi-nginx ./nginx
  - docker build -t vikram276/multi-server ./server
  - docker build -t vikram276/multi-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to dockerhub
  - docker push vikram276/multi-client
  - docker push vikram276/multi-nginx
  - docker push vikram276/multi-server
  - docker push vikram276/multi-worker
